# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af811a34de2d6f2c3c400ee4ac89eb953c4a8387901eb0f7ae02394d29fc8541d029d132accb5dbe01829e71f769c063a419bd077c45ba27f0051a173379c7a0

test:
  secret_key_base: 79d8926d5180531512c8ee376e681726511caf180422fde70603243dc62cb4d98cce7e10c635ed729ee57e513c89256305e1ce8833a6678c8246224af89317fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
